[package]
name = "candle-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
candle-core = "0.8.4"
candle-transformers = "0.8.4"
candle-nn = "0.8.4"
clap = { version = "4.2.4", features = ["derive"] }
hf-hub = "0.4.2"
tokenizers = { version = "0.21.1", default-features = false, features = [
  "onig",
] }
serde_json = "1.0.140"
tantivy = "0.24.0"
tracing = "0.1.37"
tracing-chrome = "0.7.1"
tracing-subscriber = "0.3.7"
faiss = { version = "0.12.1", features = ["static"] }
